### ISSUE TITLE
Новые шаблоны titlepage

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [mirea-ninja/Latex-Template-for-Report-Diploma-Thesis#2]
Добавить шаблоны титульных листов доклада, отчета,  лабораторной работы и т.д.

**Comment by Stulk3** [comment]
Дело в том, что это довольно бесполезное дело, поскольку практически в каждом вузе свои титульные листы, они могут отличаться настолько, что придется практически полностью переписывать разметку. Мой хороший товарищ заниматься сейчас разработкой софта для генерации отчетов, более приветливого к пользователю нежели LaTeX. Как только он появится я скину его сюда, спасибо
