### ISSUE TITLE
Подсветка листинга кода

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [mirea-ninja/Latex-Template-for-Report-Diploma-Thesis#4]
Добавить подсветку синтаксиса в листингах с исходным кодом.

**Comment by Stulk3** [comment]
В самом шаблоне я показал как можно использовать minted, это пакет со встроенной подсветкой кода, поэтому если нужно сделать подсветку, то нужно просто указать после /minted {Язык Программирования}. Обязательно добавлю несколько примеров в шаблон, спасибо
